//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="requestInputSoap", Namespace="http://tempuri.org/")]
public partial class requestInput : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback Input_ItemDataOperationCompleted;
    
    /// <remarks/>
    public requestInput() {
        this.Url = "http://10.58.82.111/Remarketting/requestInput.asmx";
    }
    
    /// <remarks/>
    public event Input_ItemDataCompletedEventHandler Input_ItemDataCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Input_ItemData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Input_ItemData(string SystemName, string Title, string ImageLead, string URL, string DataSet) {
        object[] results = this.Invoke("Input_ItemData", new object[] {
                    SystemName,
                    Title,
                    ImageLead,
                    URL,
                    DataSet});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInput_ItemData(string SystemName, string Title, string ImageLead, string URL, string DataSet, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Input_ItemData", new object[] {
                    SystemName,
                    Title,
                    ImageLead,
                    URL,
                    DataSet}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndInput_ItemData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Input_ItemDataAsync(string SystemName, string Title, string ImageLead, string URL, string DataSet) {
        this.Input_ItemDataAsync(SystemName, Title, ImageLead, URL, DataSet, null);
    }
    
    /// <remarks/>
    public void Input_ItemDataAsync(string SystemName, string Title, string ImageLead, string URL, string DataSet, object userState) {
        if ((this.Input_ItemDataOperationCompleted == null)) {
            this.Input_ItemDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInput_ItemDataOperationCompleted);
        }
        this.InvokeAsync("Input_ItemData", new object[] {
                    SystemName,
                    Title,
                    ImageLead,
                    URL,
                    DataSet}, this.Input_ItemDataOperationCompleted, userState);
    }
    
    private void OnInput_ItemDataOperationCompleted(object arg) {
        if ((this.Input_ItemDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Input_ItemDataCompleted(this, new Input_ItemDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void Input_ItemDataCompletedEventHandler(object sender, Input_ItemDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Input_ItemDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Input_ItemDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
